FROM node:18-alpine

WORKDIR /app

# Copy everything from Parking_frontend
COPY . .

# Install dependencies
RUN npm install --production

# Expose port
EXPOSE 5000

# Start backend
CMD ["node", "server/index.js"]