FROM node:18-alpine

WORKDIR /app

# Copy package.json from the server folder
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Copy server code
COPY server/ ./server/

# Expose port
EXPOSE 5000

# Start backend
CMD ["node", "server/index.js"]
